<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/HelloWorld.proto

namespace GPBMetadata\Protos;

class HelloWorld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac2010a1770726f746f732f48656c6c6f576f726c642e70726f746f1207" .
            "6465762e66796e221f0a0f53617948656c6c6f52657175657374120c0a04" .
            "6e616d6518012001280922210a1053617948656c6c6f526573706f6e7365" .
            "120d0a057265706c79180120012809324d0a0a48656c6c6f576f726c6412" .
            "3f0a0853617948656c6c6f12182e6465762e66796e2e53617948656c6c6f" .
            "526571756573741a192e6465762e66796e2e53617948656c6c6f52657370" .
            "6f6e73654203d00201620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

