<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/HelloWorld.proto

namespace Dev\Fyn;

/**
 * Protobuf type <code>dev.fyn.HelloWorld</code>
 */
interface HelloWorldInterface
{
    /**
     * Method <code>sayHello</code>
     *
     * @param \Dev\Fyn\SayHelloRequest $request
     * @return \Dev\Fyn\SayHelloResponse
     */
    public function sayHello(\Dev\Fyn\SayHelloRequest $request);

}

